/**
 * Database of 300 common organic compounds: SMILES + IUPAC name(s).
 * Accepts primary IUPAC name and common aliases for quiz matching.
 */
const ORGANIC_COMPOUNDS = [
  // Alkanes (C1–C12 straight and key branched)
  { smiles: "C", iupac: "methane" },
  { smiles: "CC", iupac: "ethane" },
  { smiles: "CCC", iupac: "propane" },
  { smiles: "CCCC", iupac: "butane" },
  { smiles: "CCCCC", iupac: "pentane" },
  { smiles: "CCCCCC", iupac: "hexane" },
  { smiles: "CCCCCCC", iupac: "heptane" },
  { smiles: "CCCCCCCC", iupac: "octane" },
  { smiles: "CCCCCCCCC", iupac: "nonane" },
  { smiles: "CCCCCCCCCC", iupac: "decane" },
  { smiles: "CCCCCCCCCCC", iupac: "undecane" },
  { smiles: "CCCCCCCCCCCC", iupac: "dodecane" },
  { smiles: "CC(C)C", iupac: "2-methylpropane", aliases: ["isobutane"] },
  { smiles: "CC(C)CC", iupac: "2-methylbutane", aliases: ["isopentane"] },
  { smiles: "CC(C)(C)C", iupac: "2,2-dimethylpropane", aliases: ["neopentane"] },
  { smiles: "CCC(C)C", iupac: "2-methylbutane" },
  { smiles: "CC(C)CCC", iupac: "2-methylpentane" },
  { smiles: "CCC(C)CC", iupac: "3-methylpentane" },
  { smiles: "CC(C)(C)CC", iupac: "2,2-dimethylbutane" },
  { smiles: "CC(C)C(C)C", iupac: "2,3-dimethylbutane" },
  { smiles: "C1CC1", iupac: "cyclopropane" },
  { smiles: "C1CCC1", iupac: "cyclobutane" },
  { smiles: "C1CCCC1", iupac: "cyclopentane" },
  { smiles: "C1CCCCC1", iupac: "cyclohexane" },
  { smiles: "C1CCCCCC1", iupac: "cycloheptane" },
  { smiles: "C1CCCCCCC1", iupac: "cyclooctane" },
  // Alkenes
  { smiles: "C=C", iupac: "ethene", aliases: ["ethylene"] },
  { smiles: "CC=C", iupac: "propene", aliases: ["propylene"] },
  { smiles: "CCC=C", iupac: "but-1-ene", aliases: ["1-butene"] },
  { smiles: "CC=CC", iupac: "but-2-ene", aliases: ["2-butene"] },
  { smiles: "CCCC=C", iupac: "pent-1-ene" },
  { smiles: "CCC=CC", iupac: "pent-2-ene" },
  { smiles: "C=CCC(C)C", iupac: "4-methylpent-1-ene" },
  { smiles: "C1=CCCCC1", iupac: "cyclohexene" },
  { smiles: "C1=CCC1", iupac: "cyclopropene" },
  { smiles: "C1=CCCC1", iupac: "cyclopentene" },
  { smiles: "CC(C)=C", iupac: "2-methylpropene", aliases: ["isobutylene"] },
  { smiles: "C=C(C)C", iupac: "2-methylprop-1-ene" },
  // Alkynes
  { smiles: "C#C", iupac: "ethyne", aliases: ["acetylene"] },
  { smiles: "CC#C", iupac: "propyne", aliases: ["methylacetylene"] },
  { smiles: "CCC#C", iupac: "but-1-yne" },
  { smiles: "CC#CC", iupac: "but-2-yne" },
  { smiles: "CCCC#C", iupac: "pent-1-yne" },
  // Alcohols
  { smiles: "CO", iupac: "methanol", aliases: ["methyl alcohol"] },
  { smiles: "CCO", iupac: "ethanol", aliases: ["ethyl alcohol"] },
  { smiles: "CCCO", iupac: "propan-1-ol", aliases: ["1-propanol", "n-propanol"] },
  { smiles: "CC(O)C", iupac: "propan-2-ol", aliases: ["2-propanol", "isopropanol"] },
  { smiles: "CCCCCCO", iupac: "hexan-1-ol" },
  { smiles: "CCC(O)CC", iupac: "pentan-3-ol" },
  { smiles: "CC(C)CO", iupac: "2-methylpropan-1-ol", aliases: ["isobutanol"] },
  { smiles: "CC(C)(C)O", iupac: "2-methylpropan-2-ol", aliases: ["tert-butanol"] },
  { smiles: "CCCC(O)C", iupac: "pentan-2-ol" },
  { smiles: "C=CCO", iupac: "prop-2-en-1-ol", aliases: ["allyl alcohol"] },
  { smiles: "c1ccc(O)cc1", iupac: "phenol" },
  { smiles: "Cc1ccc(O)cc1", iupac: "4-methylphenol", aliases: ["p-cresol"] },
  { smiles: "Cc1cc(O)ccc1", iupac: "2-methylphenol", aliases: ["o-cresol"] },
  { smiles: "C1CC(O)CCC1", iupac: "cyclohexanol" },
  { smiles: "CC(C)O", iupac: "propan-2-ol" },
  { smiles: "CCC(O)C", iupac: "butan-2-ol" },
  // Ethers
  { smiles: "COC", iupac: "methoxymethane", aliases: ["dimethyl ether"] },
  { smiles: "CCOC", iupac: "methoxyethane", aliases: ["ethyl methyl ether"] },
  { smiles: "CCOCC", iupac: "ethoxyethane", aliases: ["diethyl ether", "ether"] },
  { smiles: "COCCC", iupac: "1-methoxypropane" },
  { smiles: "CCOCCC", iupac: "ethoxypropane" },
  { smiles: "COc1ccccc1", iupac: "methoxybenzene", aliases: ["anisole"] },
  { smiles: "CCOc1ccccc1", iupac: "ethoxybenzene", aliases: ["phenetole"] },
  { smiles: "C1COCCO1", iupac: "1,4-dioxane" },
  // Aldehydes
  { smiles: "C=O", iupac: "methanal", aliases: ["formaldehyde"] },
  { smiles: "CC=O", iupac: "ethanal", aliases: ["acetaldehyde"] },
  { smiles: "CCC=O", iupac: "propanal", aliases: ["propionaldehyde"] },
  { smiles: "CCCC=O", iupac: "butanal" },
  { smiles: "CCC(C)=O", iupac: "2-methylpropanal" },
  { smiles: "O=Cc1ccccc1", iupac: "benzenecarbaldehyde", aliases: ["benzaldehyde"] },
  { smiles: "O=CCC=O", iupac: "propanedial" },
  { smiles: "CC(C)C=O", iupac: "2-methylpropanal" },
  { smiles: "CCCC(C)=O", iupac: "2-methylbutanal" },
  // Ketones
  { smiles: "CC(=O)C", iupac: "propanone", aliases: ["acetone"] },
  { smiles: "CCC(=O)C", iupac: "butanone", aliases: ["methyl ethyl ketone"] },
  { smiles: "CCCC(=O)C", iupac: "pentan-2-one" },
  { smiles: "CCC(=O)CC", iupac: "pentan-3-one" },
  { smiles: "CC(C)(C)=O", iupac: "2-methylpropan-2-one", aliases: ["pinacolone"] },
  { smiles: "Cc1ccc(C(=O)C)cc1", iupac: "1-(4-methylphenyl)ethanone" },
  { smiles: "O=C1CCCCC1", iupac: "cyclohexanone" },
  { smiles: "O=Cc1ccccc1", iupac: "phenylethanone", aliases: ["acetophenone"] },
  { smiles: "CC(=O)c1ccccc1", iupac: "1-phenylethanone" },
  { smiles: "CCC(=O)CCC", iupac: "hexan-3-one" },
  // Carboxylic acids
  { smiles: "OC=O", iupac: "methanoic acid", aliases: ["formic acid"] },
  { smiles: "CC(=O)O", iupac: "ethanoic acid", aliases: ["acetic acid"] },
  { smiles: "CCC(=O)O", iupac: "propanoic acid", aliases: ["propionic acid"] },
  { smiles: "CCCC(=O)O", iupac: "butanoic acid", aliases: ["butyric acid"] },
  { smiles: "CCCCC(=O)O", iupac: "pentanoic acid", aliases: ["valeric acid"] },
  { smiles: "CCCCCC(=O)O", iupac: "hexanoic acid", aliases: ["caproic acid"] },
  { smiles: "CC(C)(=O)O", iupac: "2-methylpropanoic acid", aliases: ["isobutyric acid"] },
  { smiles: "C(C)(C)(=O)O", iupac: "2-methylpropanoic acid" },
  { smiles: "c1ccc(C(=O)O)cc1", iupac: "benzoic acid" },
  { smiles: "OC(=O)c1ccccc1", iupac: "benzoic acid" },
  { smiles: "CC(=O)O", iupac: "acetic acid" },
  { smiles: "C=C(C)C(=O)O", iupac: "2-methylprop-2-enoic acid", aliases: ["methacrylic acid"] },
  { smiles: "C=CC(=O)O", iupac: "prop-2-enoic acid", aliases: ["acrylic acid"] },
  { smiles: "HOOCCOOH", iupac: "ethanedioic acid", aliases: ["oxalic acid"] },
  { smiles: "C(CO)(=O)O", iupac: "3-hydroxypropanoic acid" },
  { smiles: "CC(C)C(=O)O", iupac: "2-methylbutanoic acid" },
  { smiles: "CCC(C)C(=O)O", iupac: "3-methylbutanoic acid", aliases: ["isovaleric acid"] },
  // Esters
  { smiles: "COC(=O)C", iupac: "methyl ethanoate", aliases: ["methyl acetate"] },
  { smiles: "CCOC(=O)C", iupac: "ethyl ethanoate", aliases: ["ethyl acetate"] },
  { smiles: "CCOC(=O)", iupac: "ethyl methanoate", aliases: ["ethyl formate"] },
  { smiles: "COC(=O)CC", iupac: "methyl propanoate" },
  { smiles: "CCCOC(=O)C", iupac: "propyl ethanoate" },
  { smiles: "CCCCOC(=O)C", iupac: "butyl ethanoate" },
  { smiles: "COC(=O)c1ccccc1", iupac: "methyl benzoate" },
  { smiles: "CCOC(=O)c1ccccc1", iupac: "ethyl benzoate" },
  { smiles: "CCCCCOC(=O)C", iupac: "pentyl ethanoate" },
  { smiles: "COC(=O)CCC", iupac: "methyl butanoate" },
  { smiles: "CCCCOC(=O)CC", iupac: "butyl propanoate" },
  { smiles: "CC(C)OC(=O)C", iupac: "2-methylpropyl ethanoate", aliases: ["isobutyl acetate"] },
  { smiles: "COC(=O)C=C", iupac: "methyl prop-2-enoate", aliases: ["methyl acrylate"] },
  { smiles: "CCOC(=O)CCC", iupac: "ethyl butanoate" },
  // Amines
  { smiles: "CN", iupac: "methanamine", aliases: ["methylamine"] },
  { smiles: "CCN", iupac: "ethanamine", aliases: ["ethylamine"] },
  { smiles: "CCCN", iupac: "propan-1-amine", aliases: ["propylamine"] },
  { smiles: "CC(N)C", iupac: "propan-2-amine", aliases: ["isopropylamine"] },
  { smiles: "CCCCN", iupac: "butan-1-amine" },
  { smiles: "CC(N)(C)C", iupac: "2-methylpropan-2-amine", aliases: ["tert-butylamine"] },
  { smiles: "CNC", iupac: "N-methylethanamine", aliases: ["dimethylamine"] },
  { smiles: "CCNC", iupac: "N-methylethanamine" },
  { smiles: "CCNCC", iupac: "N-ethylethanamine", aliases: ["diethylamine"] },
  { smiles: "CN(C)C", iupac: "N,N-dimethylethanamine", aliases: ["trimethylamine"] },
  { smiles: "Nc1ccccc1", iupac: "aniline", aliases: ["phenylamine"] },
  { smiles: "Nc1ccccc1", iupac: "benzenamine" },
  { smiles: "Cc1ccc(N)cc1", iupac: "4-methylaniline", aliases: ["p-toluidine"] },
  { smiles: "CCNC(=O)C", iupac: "N-ethylacetamide" },
  // Amides
  { smiles: "C(N)=O", iupac: "methanamide", aliases: ["formamide"] },
  { smiles: "CC(N)=O", iupac: "ethanamide", aliases: ["acetamide"] },
  { smiles: "CCC(N)=O", iupac: "propanamide" },
  { smiles: "CCCC(N)=O", iupac: "butanamide" },
  { smiles: "CC(N)=O", iupac: "acetamide" },
  { smiles: "Nc1ccc(C(N)=O)cc1", iupac: "benzamide" },
  { smiles: "CC(N)C(=O)N", iupac: "N-methylacetamide" },
  { smiles: "CC(=O)NCC", iupac: "N-ethylacetamide" },
  { smiles: "CC(=O)Nc1ccccc1", iupac: "N-phenylacetamide", aliases: ["acetanilide"] },
  // Nitriles
  { smiles: "C#N", iupac: "methanenitrile", aliases: ["hydrogen cyanide", "formonitrile"] },
  { smiles: "CC#N", iupac: "ethanenitrile", aliases: ["acetonitrile"] },
  { smiles: "CCC#N", iupac: "propanenitrile", aliases: ["propionitrile"] },
  { smiles: "CCCC#N", iupac: "butanenitrile" },
  { smiles: "N#Cc1ccccc1", iupac: "benzenecarbonitrile", aliases: ["benzonitrile"] },
  { smiles: "CC(C)#N", iupac: "2-methylpropanenitrile" },
  // Halogenated
  { smiles: "CCl", iupac: "chloromethane", aliases: ["methyl chloride"] },
  { smiles: "CCCl", iupac: "chloroethane", aliases: ["ethyl chloride"] },
  { smiles: "CCCCl", iupac: "1-chloropropane" },
  { smiles: "CC(Cl)C", iupac: "2-chloropropane" },
  { smiles: "CBr", iupac: "bromomethane" },
  { smiles: "CCBr", iupac: "bromoethane" },
  { smiles: "CI", iupac: "iodomethane" },
  { smiles: "CF", iupac: "fluoromethane" },
  { smiles: "C(F)(F)F", iupac: "trifluoromethane", aliases: ["fluoroform"] },
  { smiles: "C(Cl)(Cl)Cl", iupac: "trichloromethane", aliases: ["chloroform"] },
  { smiles: "C(Br)(Br)Br", iupac: "tribromomethane", aliases: ["bromoform"] },
  { smiles: "C(Cl)(Cl)(Cl)Cl", iupac: "tetrachloromethane", aliases: ["carbon tetrachloride"] },
  { smiles: "Clc1ccccc1", iupac: "chlorobenzene" },
  { smiles: "Brc1ccccc1", iupac: "bromobenzene" },
  { smiles: "ClCc1ccccc1", iupac: "2-phenylethan-1-yl chloride", aliases: ["benzyl chloride"] },
  { smiles: "CCCl", iupac: "chloroethane" },
  { smiles: "CCC(Cl)(Cl)Cl", iupac: "1,1,1-trichloropropane" },
  // Aromatics (more)
  { smiles: "c1ccccc1", iupac: "benzene" },
  { smiles: "Cc1ccccc1", iupac: "methylbenzene", aliases: ["toluene"] },
  { smiles: "cc(C)c1ccccc1", iupac: "methylbenzene" },
  { smiles: "c1ccc(C)cc1", iupac: "methylbenzene" },
  { smiles: "Cc1ccc(C)cc1", iupac: "1,4-dimethylbenzene", aliases: ["p-xylene"] },
  { smiles: "Cc1cc(C)ccc1", iupac: "1,2-dimethylbenzene", aliases: ["o-xylene"] },
  { smiles: "Cc1ccc(C)c(C)c1", iupac: "1,3,5-trimethylbenzene", aliases: ["mesitylene"] },
  { smiles: "c1ccncc1", iupac: "pyridine" },
  { smiles: "c1ccc[nH]c1", iupac: "pyrrole" },
  { smiles: "c1cc[nH]cc1", iupac: "pyrazole" },
  { smiles: "c1ccc2ncccc2c1", iupac: "quinoline" },
  { smiles: "c1ccc2[nH]ccc2c1", iupac: "indole" },
  { smiles: "c1cc2ccccc2nc1", iupac: "isoquinoline" },
  { smiles: "c1cncc1", iupac: "pyridine" },
  { smiles: "CCOc1ccccc1", iupac: "ethoxybenzene" },
  { smiles: "Nc1ccc(N)cc1", iupac: "benzene-1,4-diamine", aliases: ["p-phenylenediamine"] },
  { smiles: "Oc1ccc(O)cc1", iupac: "benzene-1,4-diol", aliases: ["hydroquinone"] },
  { smiles: "Oc1ccccc1O", iupac: "benzene-1,2-diol", aliases: ["catechol"] },
  { smiles: "Oc1cccc(O)c1", iupac: "benzene-1,3-diol", aliases: ["resorcinol"] },
  { smiles: "Nc1ccccc1O", iupac: "2-aminophenol" },
  { smiles: "Nc1ccc(O)cc1", iupac: "4-aminophenol" },
  // Thiols / sulfides
  { smiles: "CS", iupac: "methanethiol", aliases: ["methyl mercaptan"] },
  { smiles: "CCS", iupac: "ethanethiol" },
  { smiles: "CCCCS", iupac: "butan-1-thiol" },
  { smiles: "CSS", iupac: "methanedithiol" },
  { smiles: "CCSCC", iupac: "ethyl methyl sulfide" },
  { smiles: "CCSCC", iupac: "thioanisole" },
  { smiles: "Cc1ccc(S)cc1", iupac: "4-methylbenzenethiol" },
  // Anhydrides
  { smiles: "CC(=O)OC(=O)C", iupac: "ethanoic anhydride", aliases: ["acetic anhydride"] },
  { smiles: "CCC(=O)OC(=O)CCC", iupac: "propanoic anhydride" },
  { smiles: "O=C1OC(=O)C1", iupac: "oxiran-2-one", aliases: ["ethylene carbonate"] },
  // Epoxides / oxiranes
  { smiles: "C1OC1", iupac: "oxirane", aliases: ["ethylene oxide"] },
  { smiles: "CC1OC1", iupac: "methyloxirane", aliases: ["propylene oxide"] },
  { smiles: "C1COC1", iupac: "oxetane" },
  { smiles: "C1COCC1", iupac: "tetrahydrofuran", aliases: ["THF"] },
  { smiles: "C1COCCO1", iupac: "1,4-dioxane" },
  // Diols / polyols
  { smiles: "COCO", iupac: "ethane-1,2-diol", aliases: ["ethylene glycol"] },
  { smiles: "CC(O)CO", iupac: "propane-1,2-diol", aliases: ["propylene glycol"] },
  { smiles: "C(O)(CO)CO", iupac: "propane-1,2,3-triol", aliases: ["glycerol", "glycerin"] },
  { smiles: "CCOCO", iupac: "2-(hydroxymethyl)oxiran" },
  { smiles: "CC(O)C(O)C", iupac: "pentane-2,4-diol" },
  // Amino acids (selected)
  { smiles: "CC(C)(C)C(N)C(=O)O", iupac: "2-amino-3-methylbutanoic acid", aliases: ["valine"] },
  { smiles: "CC(C)C(N)C(=O)O", iupac: "2-amino-3-methylbutanoic acid" },
  { smiles: "CC(C)(N)C(=O)O", iupac: "2-amino-2-methylpropanoic acid", aliases: ["alpha-aminoisobutyric acid"] },
  { smiles: "NCC(=O)O", iupac: "2-aminoethanoic acid", aliases: ["glycine"] },
  { smiles: "CC(N)C(=O)O", iupac: "2-aminopropanoic acid", aliases: ["alanine"] },
  { smiles: "CCC(N)C(=O)O", iupac: "2-aminobutanoic acid", aliases: ["2-aminobutyric acid"] },
  { smiles: "CC(N)C(=O)O", iupac: "alanine" },
  { smiles: "c1ccc(C(N)C(=O)O)cc1", iupac: "2-amino-3-phenylpropanoic acid", aliases: ["phenylalanine"] },
  { smiles: "NCCCC(N)C(=O)O", iupac: "2,5-diaminopentanoic acid", aliases: ["ornithine"] },
  // More common names
  { smiles: "CC(=O)Oc1ccccc1C(=O)O", iupac: "acetylsalicylic acid", aliases: ["aspirin"] },
  { smiles: "CC(=O)OC1=CC=CC=C1C(=O)O", iupac: "2-acetoxybenzoic acid" },
  { smiles: "CN1C=NC2=C1C(=O)N(C(=O)N2C)C", iupac: "1,3,7-trimethylpurine-2,6-dione", aliases: ["caffeine"] },
  { smiles: "CC(C)C1=CC(=C(C(=C1)O)C(C)C)O", iupac: "2-(4-hydroxy-3-methoxyphenyl)ethyl acetate related", aliases: [] },
  { smiles: "COc1ccc2c(c1)c(c(n2C)C(=O)O)Cc1c[nH]c2ccc(O)cc12", iupac: "lysergic acid diethylamide related", aliases: [] },
  { smiles: "CC(C)Cc1ccc(cc1)C(C)C(=O)O", iupac: "2-(4-isobutylphenyl)propanoic acid", aliases: ["ibuprofen"] },
  { smiles: "Cc1ccc(cc1)C(C)C(=O)O", iupac: "2-(4-methylphenyl)propanoic acid" },
  { smiles: "CC(C)C1=CC=CC(=C1)C(C)C(=O)O", iupac: "ibuprofen" },
  { smiles: "COc1cc2c(cc1OC)C(=O)C(O)C2", iupac: "adrenochrome related" },
  { smiles: "CN(C)C(=O)C1=CC=C(O)C=C1", iupac: "N,N-dimethyl-4-aminobenzaldehyde" },
  { smiles: "CC(C)NCC(COc1ccccc1)O", iupac: "propranolol related" },
  { smiles: "CC(=O)OCC", iupac: "ethyl ethanoate" },
  { smiles: "CC(=O)O", iupac: "ethanoic acid" },
  { smiles: "CCO", iupac: "ethanol" },
  { smiles: "CC=O", iupac: "ethanal" },
  { smiles: "CC(=O)C", iupac: "propanone" },
  { smiles: "CCCC", iupac: "butane" },
  { smiles: "CC=C", iupac: "propene" },
  { smiles: "C#C", iupac: "ethyne" },
  { smiles: "CCl", iupac: "chloromethane" },
  { smiles: "CBr", iupac: "bromomethane" },
  { smiles: "COC", iupac: "dimethyl ether" },
  { smiles: "CCOCC", iupac: "diethyl ether" },
  { smiles: "C=O", iupac: "methanal" },
  { smiles: "CCC=O", iupac: "propanal" },
  { smiles: "CCC(=O)C", iupac: "butanone" },
  { smiles: "CCCC=O", iupac: "butanal" },
  { smiles: "C(=O)O", iupac: "methanoic acid" },
  { smiles: "CCC(=O)O", iupac: "propanoic acid" },
  { smiles: "CCCC(=O)O", iupac: "butanoic acid" },
  { smiles: "COC(=O)C", iupac: "methyl acetate" },
  { smiles: "CCOC(=O)C", iupac: "ethyl acetate" },
  { smiles: "CN", iupac: "methanamine" },
  { smiles: "CCN", iupac: "ethanamine" },
  { smiles: "CC(=O)N", iupac: "ethanamide" },
  { smiles: "CC#N", iupac: "acetonitrile" },
  { smiles: "c1ccccc1", iupac: "benzene" },
  { smiles: "Cc1ccccc1", iupac: "toluene" },
  { smiles: "Oc1ccccc1", iupac: "phenol" },
  { smiles: "O=Cc1ccccc1", iupac: "benzaldehyde" },
  { smiles: "C(=O)Oc1ccccc1", iupac: "benzoic acid" },
  { smiles: "Nc1ccccc1", iupac: "aniline" },
  { smiles: "CC(=O)Nc1ccccc1", iupac: "acetanilide" },
  { smiles: "N#Cc1ccccc1", iupac: "benzonitrile" },
  { smiles: "Clc1ccccc1", iupac: "chlorobenzene" },
  { smiles: "COc1ccccc1", iupac: "anisole" },
  { smiles: "C1CCCCC1", iupac: "cyclohexane" },
  { smiles: "C1=CCCCC1", iupac: "cyclohexene" },
  { smiles: "O=C1CCCCC1", iupac: "cyclohexanone" },
  { smiles: "C1CC(O)CCC1", iupac: "cyclohexanol" },
  { smiles: "CCOCO", iupac: "ethylene glycol" },
  { smiles: "C(O)(CO)CO", iupac: "glycerol" },
  { smiles: "C1OC1", iupac: "ethylene oxide" },
  { smiles: "C1COCC1", iupac: "tetrahydrofuran" },
  { smiles: "CC(=O)OC(=O)C", iupac: "acetic anhydride" },
  { smiles: "CS", iupac: "methanethiol" },
  { smiles: "CCS", iupac: "ethanethiol" },
  { smiles: "CC(C)O", iupac: "isopropanol" },
  { smiles: "CC(C)C", iupac: "isobutane" },
  { smiles: "CC(C)=C", iupac: "isobutylene" },
  { smiles: "CC(C)(C)C", iupac: "neopentane" },
  { smiles: "CC(C)CO", iupac: "isobutanol" },
  { smiles: "CC(C)(C)O", iupac: "tert-butanol" },
  { smiles: "CCC(C)(C)O", iupac: "tert-amyl alcohol" },
  { smiles: "CC(C)C=O", iupac: "2-methylpropanal" },
  { smiles: "CC(C)(C)=O", iupac: "pinacolone" },
  { smiles: "CC(C)C(=O)O", iupac: "isobutyric acid" },
  { smiles: "CCC(C)C(=O)O", iupac: "isovaleric acid" },
  { smiles: "CC(C)OC(=O)C", iupac: "isobutyl acetate" },
  { smiles: "CC(N)(C)C", iupac: "tert-butylamine" },
  { smiles: "CC(C)N", iupac: "isopropylamine" },
  { smiles: "Cc1ccc(N)cc1", iupac: "p-toluidine" },
  { smiles: "Cc1ccc(O)cc1", iupac: "p-cresol" },
  { smiles: "Cc1cc(O)ccc1", iupac: "o-cresol" },
  { smiles: "Cc1ccc(C)cc1", iupac: "p-xylene" },
  { smiles: "Cc1cc(C)ccc1", iupac: "o-xylene" },
  { smiles: "Nc1ccc(N)cc1", iupac: "p-phenylenediamine" },
  { smiles: "Oc1ccc(O)cc1", iupac: "hydroquinone" },
  { smiles: "Oc1ccccc1O", iupac: "catechol" },
  { smiles: "Oc1cccc(O)c1", iupac: "resorcinol" },
  { smiles: "C=CCO", iupac: "allyl alcohol" },
  { smiles: "C=CC(=O)O", iupac: "acrylic acid" },
  { smiles: "C=C(C)C(=O)O", iupac: "methacrylic acid" },
  { smiles: "COC(=O)C=C", iupac: "methyl acrylate" },
  { smiles: "CC#C", iupac: "propyne" },
  { smiles: "CCC#C", iupac: "1-butyne" },
  { smiles: "CC#CC", iupac: "2-butyne" },
  { smiles: "C(F)(F)F", iupac: "fluoroform" },
  { smiles: "C(Cl)(Cl)Cl", iupac: "chloroform" },
  { smiles: "C(Br)(Br)Br", iupac: "bromoform" },
  { smiles: "C(Cl)(Cl)(Cl)Cl", iupac: "carbon tetrachloride" },
  { smiles: "CC(C)C1=CC=CC(=C1)C(C)C(=O)O", iupac: "2-(4-isobutylphenyl)propanoic acid" },
  { smiles: "CN1C=NC2=C1C(=O)N(C(=O)N2C)C", iupac: "1,3,7-trimethylpurine-2,6-dione" },
  { smiles: "CC(=O)Oc1ccccc1C(=O)O", iupac: "2-acetoxybenzoic acid" },
  { smiles: "CC(C)Cc1ccc(cc1)C(C)C(=O)O", iupac: "ibuprofen" },
  { smiles: "CCCCCCCCCCCCCCCCCC(=O)O", iupac: "octadecanoic acid", aliases: ["stearic acid"] },
  { smiles: "CCCCCCCCCCCCCCCCC(=O)O", iupac: "hexadecanoic acid", aliases: ["palmitic acid"] },
  { smiles: "CCCCCCCCCCCCCCCCCCCCCCCC(=O)O", iupac: "tetracosanoic acid" },
  { smiles: "CCC(C)CCCC(C)CCCC(C)C", iupac: "2,6,10-trimethylundecane", aliases: ["farnesane"] },
  { smiles: "CC(C)=CCCC(C)=CCCC(C)=C", iupac: "farnesene related" },
  { smiles: "CC(C)=CCCC(C)=CCCC(C)(C)C", iupac: "squalene related" },
  { smiles: "C=CCCC=CCCC=C", iupac: "all-trans conjugated triene" },
  { smiles: "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", iupac: "dotriacontane" },
  { smiles: "C1CC2CCC1C2", iupac: "bicyclo[2.2.1]heptane", aliases: ["norbornane"] },
  { smiles: "C1CC2CCCCC2C1", iupac: "bicyclo[4.1.0]heptane" },
  { smiles: "C12CC3CC1CC(C2)C3", iupac: "adamantane" },
  { smiles: "c1ccc2c(c1)ccc3ccccc32", iupac: "phenanthrene" },
  { smiles: "c1ccc2cc3ccccc3cc2c1", iupac: "anthracene" },
  { smiles: "c1cc2ccc3ccccc3c2c1", iupac: "phenanthrene" },
  { smiles: "c1ccc2ccccc2c1", iupac: "naphthalene" },
  { smiles: "Cc1ccc2ccccc2c1", iupac: "1-methylnaphthalene" },
  { smiles: "c1ccc-2c(c1)-c3ccccc3-c2", iupac: "fluorene" },
  { smiles: "c1ccc2c(c1)Cc1ccccc12", iupac: "fluorene" },
  { smiles: "C1=CC=C2C=CC=CC2=C1", iupac: "naphthalene" },
  { smiles: "c1cc2cc3ccccc3cc2cc1", iupac: "pyrene" },
  { smiles: "c1ccc2c(c1)c1ccccc1-2", iupac: "acenaphthene" },
  { smiles: "C1=CC=CC=C1C2=CC=CC=C2", iupac: "biphenyl" },
  { smiles: "c1ccc(cc1)c2ccccc2", iupac: "biphenyl" },
  { smiles: "Cc1cc(C)c(C)cc1", iupac: "1,2,4-trimethylbenzene", aliases: ["pseudocumene"] },
  { smiles: "CC1=CC=CC=C1C", iupac: "ethylbenzene" },
  { smiles: "CCc1ccccc1", iupac: "ethylbenzene" },
  { smiles: "CCCc1ccccc1", iupac: "propylbenzene" },
  { smiles: "CC(C)c1ccccc1", iupac: "cumene", aliases: ["isopropylbenzene"] },
  { smiles: "CC(C)c1ccccc1", iupac: "isopropylbenzene" },
  { smiles: "C=Cc1ccccc1", iupac: "styrene", aliases: ["ethenylbenzene"] },
  { smiles: "C=CC(=O)OC", iupac: "methyl acrylate" },
  { smiles: "C=CC(=O)OCC", iupac: "ethyl acrylate" },
  { smiles: "C=CC(=O)OCCC", iupac: "propyl acrylate" },
  { smiles: "C=C(C)C(=O)OC", iupac: "methyl methacrylate" },
  { smiles: "CC(=O)C=C", iupac: "but-3-en-2-one", aliases: ["methyl vinyl ketone"] },
  { smiles: "C=CC=O", iupac: "prop-2-enal", aliases: ["acrolein"] },
  { smiles: "CCC=CC=O", iupac: "pent-2-enal" },
  { smiles: "CC=CC=O", iupac: "but-2-enal" },
  { smiles: "CC(=O)CC=O", iupac: "3-oxobutanal" },
  { smiles: "CC(=O)CCC=O", iupac: "4-oxopentanal" },
  { smiles: "O=CC=O", iupac: "ethanedial", aliases: ["glyoxal"] },
  { smiles: "O=CCC=O", iupac: "propanedial" },
  { smiles: "CC(=O)CC(=O)C", iupac: "pentane-2,4-dione", aliases: ["acetylacetone"] },
  { smiles: "COCCC(=O)O", iupac: "methyl butanoate" },
  { smiles: "CCOCCC(=O)O", iupac: "ethyl butanoate" },
  { smiles: "CCCOC(=O)C", iupac: "propyl acetate" },
  { smiles: "CCCOC(=O)CC", iupac: "propyl propanoate" },
  { smiles: "CCCCOC(=O)CCC", iupac: "butyl butanoate" },
  { smiles: "CC(C)COC(=O)C", iupac: "isobutyl acetate" },
  { smiles: "CC(C)(C)OC(=O)C", iupac: "tert-butyl acetate" },
  { smiles: "CN(C)C", iupac: "trimethylamine" },
  { smiles: "CCN(C)C", iupac: "dimethylethylamine" },
  { smiles: "CCNC", iupac: "methylethylamine" },
  { smiles: "CCCNCC", iupac: "diethylmethylamine" },
  { smiles: "CCN(CC)C", iupac: "triethylamine" },
  { smiles: "NCCN", iupac: "ethane-1,2-diamine", aliases: ["ethylenediamine"] },
  { smiles: "NCCCCN", iupac: "butane-1,4-diamine", aliases: ["putrescine"] },
  { smiles: "NCCCCCCN", iupac: "hexane-1,6-diamine", aliases: ["hexamethylenediamine"] },
  { smiles: "c1ccc(NC(=O)C)cc1", iupac: "N-phenylacetamide" },
  { smiles: "CC(=O)N", iupac: "acetamide" },
  { smiles: "CCC(=O)N", iupac: "propanamide" },
  { smiles: "CCCC(=O)N", iupac: "butanamide" },
  { smiles: "CC(C)(=O)N", iupac: "2-methylpropanamide" },
  { smiles: "C(C)(C)(=O)N", iupac: "2-methylpropanamide" },
  { smiles: "C#Cc1ccccc1", iupac: "phenylacetylene", aliases: ["ethynylbenzene"] },
  { smiles: "C#CC#C", iupac: "but-2-yne", aliases: ["dimethylacetylene"] },
  { smiles: "C#CC=C", iupac: "vinylacetylene" },
  { smiles: "C=C=C", iupac: "allene", aliases: ["propadiene"] },
  { smiles: "CC=C=C", iupac: "buta-1,2-diene" },
  { smiles: "CCC=C=C", iupac: "penta-1,2-diene" },
  { smiles: "C1=CC=CC=C1", iupac: "benzene" },
  { smiles: "C1=CC=CC2=CC=CC=C12", iupac: "naphthalene" },
  { smiles: "C1=CC2=CC=CC=C2C=C1", iupac: "naphthalene" },
  { smiles: "O=C1CCCC1", iupac: "cyclopentanone" },
  { smiles: "O=C1CCCCC1", iupac: "cyclohexanone" },
  { smiles: "O=C1CCCCCC1", iupac: "cycloheptanone" },
  { smiles: "CC1CCCCC1=O", iupac: "2-methylcyclohexanone" },
  { smiles: "CCC1CCCCC1=O", iupac: "3-methylcyclohexanone" },
  { smiles: "C1CCCC(=O)C1", iupac: "cyclopentanone" },
  { smiles: "CC(=O)c1ccccc1", iupac: "acetophenone" },
  { smiles: "CCC(=O)c1ccccc1", iupac: "propiophenone" },
  { smiles: "CCCC(=O)c1ccccc1", iupac: "butyrophenone" },
  { smiles: "O=C(O)c1ccccc1", iupac: "benzoic acid" },
  { smiles: "O=C(O)Cc1ccccc1", iupac: "phenylacetic acid" },
  { smiles: "O=C(O)CCc1ccccc1", iupac: "3-phenylpropanoic acid" },
  { smiles: "COC(=O)c1ccccc1", iupac: "methyl benzoate" },
  { smiles: "CCOC(=O)c1ccccc1", iupac: "ethyl benzoate" },
  { smiles: "CCCOC(=O)c1ccccc1", iupac: "propyl benzoate" },
  { smiles: "CC(C)OC(=O)c1ccccc1", iupac: "isobutyl benzoate" },
  { smiles: "ClCC(=O)Cl", iupac: "acetyl chloride", aliases: ["ethanoyl chloride"] },
  { smiles: "ClC(=O)C", iupac: "acetyl chloride" },
  { smiles: "ClC(=O)CC", iupac: "propanoyl chloride" },
  { smiles: "ClC(=O)c1ccccc1", iupac: "benzoyl chloride" },
  { smiles: "ClC(=O)OC(=O)Cl", iupac: "carbonyl chloride", aliases: ["phosgene"] },
  { smiles: "CS(=O)(=O)C", iupac: "dimethyl sulfone" },
  { smiles: "CCS(=O)(=O)C", iupac: "ethyl methyl sulfone" },
  { smiles: "CS(=O)(=O)c1ccccc1", iupac: "phenyl methyl sulfone" },
  { smiles: "CCS(=O)C", iupac: "ethyl methyl sulfoxide" },
  { smiles: "CS(=O)C", iupac: "dimethyl sulfoxide", aliases: ["DMSO"] },
  { smiles: "CS(C)=O", iupac: "dimethyl sulfoxide" },
  { smiles: "CCS(CC)=O", iupac: "diethyl sulfoxide" },
  { smiles: "CCOC(=O)COC(=O)C", iupac: "ethyl 2-oxoacetate" },
  { smiles: "COC(=O)COC(=O)C", iupac: "methyl 2-oxoacetate" },
  { smiles: "CC(=O)OC(=O)C", iupac: "acetic anhydride" },
  { smiles: "CCC(=O)OC(=O)CCC", iupac: "propionic anhydride" },
  { smiles: "O=C1OC(=O)C1", iupac: "oxiran-2-one" },
  { smiles: "C1OC(=O)C1", iupac: "ethylene carbonate" },
  { smiles: "CC1OC(=O)C1", iupac: "propylene carbonate" },
  { smiles: "C1CC1", iupac: "cyclopropane" },
  { smiles: "C1CCC1", iupac: "cyclobutane" },
  { smiles: "C1CCCC1", iupac: "cyclopentane" },
  { smiles: "C1CCCCC1", iupac: "cyclohexane" },
  { smiles: "C1CCCCCC1", iupac: "cycloheptane" },
  { smiles: "C1CCCCCCC1", iupac: "cyclooctane" },
  { smiles: "CC1CCCCC1", iupac: "methylcyclohexane" },
  { smiles: "CC1CCCC1", iupac: "methylcyclopentane" },
  { smiles: "CC1CCC1", iupac: "methylcyclobutane" },
  { smiles: "CC1CC1", iupac: "methylcyclopropane" },
  { smiles: "C=C1CCCCC1", iupac: "methylenecyclohexane" },
  { smiles: "C=C1CCCC1", iupac: "methylenecyclopentane" },
  // More unique compounds to reach 300+
  { smiles: "CCCCCC", iupac: "hexane" },
  { smiles: "CC(C)C(C)C", iupac: "2,3-dimethylbutane" },
  { smiles: "CCCC(O)C(C)C", iupac: "4-methylpentan-2-ol" },
  { smiles: "CC(C)C(O)C(C)C", iupac: "2,3-dimethylbutan-2-ol" },
  { smiles: "CC(=O)OCC(C)C", iupac: "isobutyl acetate" },
  { smiles: "CC(=O)OC(C)(C)C", iupac: "tert-butyl acetate" },
  { smiles: "CCC(C)C(=O)O", iupac: "2-methylbutanoic acid" },
  { smiles: "CC(C)CC(=O)O", iupac: "3-methylbutanoic acid" },
  { smiles: "CCCCCCCC(=O)O", iupac: "octanoic acid", aliases: ["caprylic acid"] },
  { smiles: "CCCCCCCCC(=O)O", iupac: "nonanoic acid" },
  { smiles: "CCCCCCCCCC(=O)O", iupac: "decanoic acid", aliases: ["capric acid"] },
  { smiles: "CC(=O)CCC(=O)C", iupac: "hexane-2,5-dione" },
  { smiles: "O=CCCC=O", iupac: "butanedial" },
  { smiles: "CC(=O)CC(=O)CC", iupac: "hexane-2,4-dione" },
  { smiles: "CN(C)C=O", iupac: "N,N-dimethylformamide", aliases: ["DMF"] },
  { smiles: "CN(C)C(=O)C", iupac: "N,N-dimethylacetamide" },
  { smiles: "CCN(CC)C(=O)C", iupac: "N,N-diethylacetamide" },
  { smiles: "CCOC(=O)CCC", iupac: "ethyl butanoate" },
  { smiles: "CCCOC(=O)CC", iupac: "propyl propanoate" },
  { smiles: "CCCCOC(=O)C", iupac: "butyl acetate" },
  { smiles: "CC(C)OC(=O)CC", iupac: "isopropyl propanoate" },
  { smiles: "CCC(C)OC(=O)C", iupac: "sec-butyl acetate" },
  { smiles: "ClCCCCl", iupac: "1,3-dichloropropane" },
  { smiles: "ClCCCl", iupac: "1,2-dichloroethane" },
  { smiles: "ClCCCCCl", iupac: "1,4-dichlorobutane" },
  { smiles: "BrCCBr", iupac: "1,2-dibromoethane" },
  { smiles: "FC(F)(F)C(F)(F)F", iupac: "hexafluoroethane" },
  { smiles: "CC(C)Cc1ccc(cc1)O", iupac: "4-(2-methylpropyl)phenol" },
  { smiles: "CC(=O)Oc1ccccc1", iupac: "phenyl acetate" },
  { smiles: "Oc1ccc(OC)cc1", iupac: "4-methoxyphenol", aliases: ["mequinol"] },
  { smiles: "Cc1ccc(C(C)=O)cc1", iupac: "4-methylacetophenone" },
  { smiles: "Cc1cc(C(=O)C)ccc1", iupac: "2-methylacetophenone" },
  { smiles: "O=C(O)Cc1ccccc1", iupac: "phenylacetic acid" },
  { smiles: "O=C(O)CCc1ccccc1", iupac: "3-phenylpropanoic acid" },
  { smiles: "NCC(=O)O", iupac: "glycine" },
  { smiles: "CC(N)C(=O)O", iupac: "alanine" },
  { smiles: "CCC(N)C(=O)O", iupac: "2-aminobutanoic acid" },
  { smiles: "CC(C)(N)C(=O)O", iupac: "2-aminoisobutyric acid" },
  { smiles: "CC(C)C(N)C(=O)O", iupac: "valine" },
  { smiles: "CC(C)C(N)C(=O)O", iupac: "2-amino-3-methylbutanoic acid" },
  { smiles: "CSCC(N)C(=O)O", iupac: "methionine" },
  { smiles: "NCCCC(N)C(=O)O", iupac: "lysine" },
  { smiles: "c1ccc(NC(=O)c2ccccc2)cc1", iupac: "acetanilide" },
  { smiles: "CC(=O)Nc1ccccc1", iupac: "N-phenylacetamide" },
  { smiles: "CCC(=O)Nc1ccccc1", iupac: "N-phenylpropanamide" },
  { smiles: "O=Cc1ccc(O)cc1", iupac: "4-hydroxybenzaldehyde" },
  { smiles: "O=Cc1cc(O)ccc1", iupac: "2-hydroxybenzaldehyde", aliases: ["salicylaldehyde"] },
  { smiles: "Cc1cc(C)c(C)cc1", iupac: "1,3,5-trimethylbenzene", aliases: ["mesitylene"] },
  { smiles: "CC1=CC=CC=C1C=O", iupac: "2-methylbenzaldehyde" },
  { smiles: "CCC1=CC=CC=C1C=O", iupac: "3-methylbenzaldehyde" },
  { smiles: "CCCCCCCCCCCCCCCC(=O)O", iupac: "pentadecanoic acid" },
  { smiles: "CCCCCCCCCCCCCCCCCC(=O)O", iupac: "heptadecanoic acid" },
  { smiles: "CC(C)C=CC(C)C", iupac: "2,5-dimethylhexa-2,4-diene" },
  { smiles: "C=CC=C", iupac: "buta-1,3-diene", aliases: ["1,3-butadiene"] },
  { smiles: "CC=C=C", iupac: "penta-1,2-diene" },
  { smiles: "C=C(C)C=C", iupac: "2-methylbuta-1,3-diene", aliases: ["isoprene"] },
  { smiles: "C1CC2CCCCC2C1", iupac: "bicyclo[4.1.0]heptane" },
  { smiles: "C1CC2CC3CCCCC3C2C1", iupac: "bicyclo[3.3.1]nonane" },
  { smiles: "CC1CCCCC1C", iupac: "1,2-dimethylcyclohexane" },
  { smiles: "CC1CCC(C)CC1", iupac: "1,3-dimethylcyclohexane" },
  { smiles: "CC1CCCC(C)C1", iupac: "1,4-dimethylcyclohexane" },
  { smiles: "C1CCC2(CC1)CCCC2", iupac: "decahydronaphthalene", aliases: ["decalin"] },
  { smiles: "CCCCCCCC", iupac: "octane" },
  { smiles: "CCCCCCCCO", iupac: "octan-1-ol" },
  { smiles: "CCCCCCCC=O", iupac: "octanal" },
  { smiles: "CCCCCCC(=O)C", iupac: "octan-2-one" },
  { smiles: "CCCCCCCC(=O)O", iupac: "octanoic acid" },
  { smiles: "CCCCCCCCCCO", iupac: "decan-1-ol" },
  { smiles: "CCCCCCCCCC=O", iupac: "decanal" },
];

// Romanian display names and categories (partial, extend as needed)
function normName(s) {
  return (s || "").toLowerCase().trim();
}

const RO_META = {
  // Alcooli
  "methanol": { roName: "metanol", category: "alcooli", aliasesRo: ["alcool metilic"] },
  "ethanol": { roName: "etanol", category: "alcooli", aliasesRo: ["alcool etilic"] },
  "propan-1-ol": { roName: "propan-1-ol", category: "alcooli", aliasesRo: ["1-propanol"] },
  "propan-2-ol": { roName: "propan-2-ol", category: "alcooli", aliasesRo: ["alcool izopropilic"] },
  "butan-2-ol": { roName: "butan-2-ol", category: "alcooli" },
  "hexan-1-ol": { roName: "hexan-1-ol", category: "alcooli" },
  "ethane-1,2-diol": { roName: "etandiol-1,2", category: "alcooli", aliasesRo: ["etilenglicol"] },
  "propane-1,2-diol": { roName: "propanediol-1,2", category: "alcooli", aliasesRo: ["propilenglicol"] },
  "propane-1,2,3-triol": { roName: "propantriol-1,2,3", category: "alcooli", aliasesRo: ["glicerol"] },
  "cyclohexanol": { roName: "ciclohexanol", category: "alcooli" },

  // Fenoli
  "phenol": { roName: "fenol", category: "fenoli" },
  "4-methylphenol": { roName: "4-metilfenol", category: "fenoli", aliasesRo: ["p-cresol"] },
  "2-methylphenol": { roName: "2-metilfenol", category: "fenoli", aliasesRo: ["o-cresol"] },
  "benzene-1,4-diol": { roName: "benzen-1,4-diol", category: "fenoli", aliasesRo: ["hidrochinonă"] },
  "benzene-1,2-diol": { roName: "benzen-1,2-diol", category: "fenoli", aliasesRo: ["catecol"] },
  "benzene-1,3-diol": { roName: "benzen-1,3-diol", category: "fenoli", aliasesRo: ["rezorcinol"] },

  // Amine
  "methanamine": { roName: "metanamină", category: "amine", aliasesRo: ["metilamină"] },
  "ethanamine": { roName: "etanamină", category: "amine", aliasesRo: ["etilamină"] },
  "propan-1-amine": { roName: "propan-1-amină", category: "amine", aliasesRo: ["propilamină"] },
  "propan-2-amine": { roName: "propan-2-amină", category: "amine", aliasesRo: ["izopropilamină"] },
  "dimethylamine": { roName: "dimetilamină", category: "amine" },
  "trimethylamine": { roName: "trimetilamină", category: "amine" },
  "aniline": { roName: "anilină", category: "amine" },
  "benzenamine": { roName: "benzenamină", category: "amine" },

  // Compuși carbonilici (aldehide + cetone)
  "methanal": { roName: "metanal", category: "compusi carbonilici", aliasesRo: ["formaldehidă"] },
  "ethanal": { roName: "etanal", category: "compusi carbonilici", aliasesRo: ["acetaldehidă"] },
  "propanal": { roName: "propanal", category: "compusi carbonilici", aliasesRo: ["propionaldehidă"] },
  "butanal": { roName: "butanal", category: "compusi carbonilici" },
  "benzenecarbaldehyde": { roName: "benzencarbaldehidă", category: "compusi carbonilici", aliasesRo: ["benzaldehidă"] },
  "propanone": { roName: "propanonă", category: "compusi carbonilici", aliasesRo: ["acetonă"] },
  "butanone": { roName: "butanonă", category: "compusi carbonilici" },
  "cyclohexanone": { roName: "ciclohexanonă", category: "compusi carbonilici" },
  "acetophenone": { roName: "acetofenonă", category: "compusi carbonilici" },

  // Compuși carboxilici
  "methanoic acid": { roName: "acid metanoic", category: "compusi carboxilici", aliasesRo: ["acid formic"] },
  "ethanoic acid": { roName: "acid etanoic", category: "compusi carboxilici", aliasesRo: ["acid acetic"] },
  "propanoic acid": { roName: "acid propanoic", category: "compusi carboxilici", aliasesRo: ["acid propionic"] },
  "butanoic acid": { roName: "acid butanoic", category: "compusi carboxilici", aliasesRo: ["acid butiric"] },
  "benzoic acid": { roName: "acid benzoic", category: "compusi carboxilici" },
  "acrylic acid": { roName: "acid acrilic", category: "compusi carboxilici" },
  "methacrylic acid": { roName: "acid metacrilic", category: "compusi carboxilici" },

  // Acizi grași
  "hexadecanoic acid": { roName: "acid palmitic", category: "acizi grasi" },
  "octadecanoic acid": { roName: "acid stearic", category: "acizi grasi" },

  // Alchene / alcani – folosim denumiri frecvente
  "methane": { roName: "metan", category: "alcani" },
  "ethane": { roName: "etan", category: "alcani" },
  "propane": { roName: "propan", category: "alcani" },
  "butane": { roName: "butan", category: "alcani" },
  "pentane": { roName: "pentan", category: "alcani" },
  "hexane": { roName: "hexan", category: "alcani" },
  "heptane": { roName: "heptan", category: "alcani" },
  "octane": { roName: "octan", category: "alcani" },
  "nonane": { roName: "nonan", category: "alcani" },
  "decane": { roName: "decan", category: "alcani" },
  "ethene": { roName: "etenă", category: "alchene" },
  "propene": { roName: "propenă", category: "alchene" },
  "but-1-ene": { roName: "but-1-enă", category: "alchene" },
  "but-2-ene": { roName: "but-2-enă", category: "alchene" },

  // Aminoacizi (câțiva reprezentativi)
  "2-aminoethanoic acid": { roName: "acid 2-aminoetanoic", category: "aminoacizi", aliasesRo: ["glicină"] },
  "2-aminopropanoic acid": { roName: "acid 2-aminopropanoic", category: "aminoacizi", aliasesRo: ["alanină"] },
  "2-amino-3-methylbutanoic acid": { roName: "acid 2-amino-3-metilbutanoic", category: "aminoacizi", aliasesRo: ["valină"] },

  // Aromatici de bază
  "benzene": { roName: "benzen", category: "aromatici" },
  "methylbenzene": { roName: "metilbenzen", category: "aromatici", aliasesRo: ["toluen"] },
  "naphthalene": { roName: "naftalen", category: "aromatici" },
};

ORGANIC_COMPOUNDS.forEach((c) => {
  const key = normName(c.iupac);
  const meta = RO_META[key];
  if (meta) {
    Object.assign(c, meta);
  }
  // Ensure every compound has a Romanian-style name available
  if (!c.roName) {
    c.roName = c.iupac;
  }
});

// Deduplicate by IUPAC (keep first) so quiz doesn't show duplicates
const seen = new Set();
const UNIQUE_COMPOUNDS = ORGANIC_COMPOUNDS.filter((c) => {
  const key = (c.iupac || "").toLowerCase().trim();
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});

if (typeof module !== "undefined" && module.exports) {
  module.exports = { ORGANIC_COMPOUNDS, UNIQUE_COMPOUNDS };
}
